# YOUR AGE IN 2090
# TAKE AGE OR YEAR OR BIRTH AS AN INPUT FROM USER AND TELL THEM WHEN THEY WILL TURN 100 YEARS OLD
# DONT USE ANY KIND OF MODULE LIKE DATETIME
# THEY THEN PROVIDE YEAR AND YOUR AGE IN THAT PARTICULAR YEAR:
# YOU ARE NOT YET BORN
# YOU SEEM TO BE OLDEST PERSON ALIVE
# YOU CAN ALSO HANDLE ANY OTHER ERROR IF POSSIBLE


