"""
RESTAURANT SORTED THEIR FOODS ACC TO THEIR CALORIES.
YOU HAVE TO REVERSE LIST OF FOOD ITEMS AND THEIR CALOIRES.
3 METHODS TO REVERSE
- INBUILT METHOD OF PYTHON
- LISTNAME[::-1] SLICING TRACK
- SWAPPING FIRST ELEMENT WITH LAST ONE AND SECOND ELEMENT 

INPUT -
"""