{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ef5de38b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter the first number to add : 100\n",
      "Enter the second number to add : 20\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : \n",
      "Enter the valid number : \n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 2\n",
      "DIFFERENCE is :  80\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 3\n",
      "MULTIPLICATIONS is :  2000\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 4\n",
      "DIVISION IS :  5\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 5\n",
      "This function is applicable for num1\n",
      "Sine 100 = -0.5063656411097588\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 6\n",
      "This function is applicable for num1\n",
      "Cosine 100 = 0.8623188722876839\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 7\n",
      "This function is applicable for num1\n",
      "Tan 100 = -0.5872139151569291\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 8\n",
      "This function is applicable for num1\n",
      "Log 100 = 4.605170185988092\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 9\n",
      "This function is applicable for num1\n",
      "Squareroot 100 = 10.0\n",
      "WELCOME TO MY CALCULATOR !!!\n",
      "Here is list of choice : \n",
      "1 : ADD\n",
      "2 : SUBTRACTION\n",
      "3 : MULTIPLICATION\n",
      "4 : DIVISION\n",
      "5 : SIN RADIAN\n",
      "6 : COS RADIAN\n",
      "7 : TAN RADIAN\n",
      "8 : LOG\n",
      "9 : SQUAREROOT\n",
      "10: EXIT\n",
      "Enter the number of your choice : 10\n",
      "Thank you for using Calculator!!!\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "\n",
    "\n",
    "class Calculator:                                                \n",
    "        \n",
    "    def __init__(self,num1, num2):                                #constructor\n",
    "        self.num1 = num1\n",
    "        self.num2 = num2\n",
    "    \n",
    "    def addition(self):                                          #methods\n",
    "        answer = self.num1 + self.num2\n",
    "        print(\"SUM is : \", answer)\n",
    "    \n",
    "    def substraction(self):\n",
    "        answer = self.num1 - self.num2\n",
    "        print(\"DIFFERENCE is : \", answer)\n",
    "    \n",
    "    def multiplication(self):\n",
    "        answer = self.num1 * self.num2\n",
    "        print(\"MULTIPLICATIONS is : \", answer)\n",
    "    \n",
    "    def division(self,):\n",
    "        answer = self.num1 // self.num2\n",
    "        print(\"DIVISION IS : \", answer)\n",
    "        \n",
    "class Scientific(Calculator):\n",
    "    \n",
    "    \n",
    "        \n",
    "    def sinrad(self):\n",
    "        print(\"This function is applicable for num1\")\n",
    "        answer = math.sin(self.num1)\n",
    "        print(f'Sine {self.num1} = {answer}')\n",
    "        \n",
    "    def cosrad(self):\n",
    "        print(\"This function is applicable for num1\")\n",
    "        answer = math.cos(self.num1)\n",
    "        print(f'Cosine {self.num1} = {answer}')\n",
    "        \n",
    "    def tanrad(self):\n",
    "        print(\"This function is applicable for num1\")\n",
    "        answer = math.tan(self.num1)\n",
    "        print(f'Tan {self.num1} = {answer}')\n",
    "        \n",
    "    def log(self):\n",
    "        print(\"This function is applicable for num1\")\n",
    "        answer = math.log(self.num1)\n",
    "        print(f'Log {self.num1} = {answer}')\n",
    "        \n",
    "    def squareroot(self):\n",
    "        print(\"This function is applicable for num1\")\n",
    "        answer = math.sqrt(self.num1)\n",
    "        print(f'Squareroot {self.num1} = {answer}')\n",
    "        \n",
    "        \n",
    "        \n",
    "\n",
    "n1 = int(input('Enter the first number to add : '))\n",
    "n2 = int(input('Enter the second number to add : '))\n",
    "calc = Calculator(n1,n2) \n",
    "sc = Scientific(n1,n2)\n",
    "#object instantiation\n",
    "choice = \"\"\n",
    "\n",
    "while True:\n",
    "    print('WELCOME TO MY CALCULATOR !!!')\n",
    "    print('Here is list of choice : ')\n",
    "    print('1 : ADD')\n",
    "    print('2 : SUBTRACTION')\n",
    "    print('3 : MULTIPLICATION')\n",
    "    print('4 : DIVISION')\n",
    "    print('5 : SIN RADIAN')\n",
    "    print('6 : COS RADIAN')\n",
    "    print('7 : TAN RADIAN')\n",
    "    print('8 : LOG')\n",
    "    print('9 : SQUAREROOT')\n",
    "    print('10: EXIT')\n",
    "    \n",
    "    try:\n",
    "        choice = int(input('Enter the number of your choice : '))\n",
    "    except:\n",
    "        print('Enter the valid number : ')        \n",
    "    if choice == 1:\n",
    "        # n1 = int(input('Enter the first number to subtract : '))\n",
    "        # n2 = int(input('Enter the second number to subtract : '))\n",
    "        calc.addition()\n",
    "    if choice == 2:\n",
    "        # n1 = int(input('Enter the first number to subtract : '))\n",
    "        # n2 = int(input('Enter the second number to subtract : '))\n",
    "        calc.substraction()\n",
    "        \n",
    "    elif choice == 3:\n",
    "        # n1 = int(input('Enter the first number to multiply : '))\n",
    "        # n2 = int(input('Enter the second number to multiply : '))\n",
    "        calc.multiplication()\n",
    "        \n",
    "    elif choice == 4:\n",
    "        # n1 = int(input('Enter the first number to divide : '))\n",
    "        # n2 = int(input('Enter the second number to divide : '))\n",
    "        calc.division()\n",
    "        \n",
    "    elif choice == 5:\n",
    "        # n = int(input('Enter the number to find its SINE in Rad : '))\n",
    "        sc.sinrad()\n",
    "             \n",
    "    elif choice == 6:\n",
    "        # n = int(input('Enter the number to find its COS in Rad : '))\n",
    "        sc.cosrad() \n",
    "    \n",
    "    elif choice == 7:\n",
    "        # n = int(input('Enter the number to find its TAN in Rad : '))\n",
    "        sc.tanrad()\n",
    "        \n",
    "    elif choice == 8:\n",
    "        # n = int(input('Enter the number to find its TAN in Rad : '))\n",
    "        sc.log()\n",
    "        \n",
    "    elif choice == 9:\n",
    "        sc.squareroot()\n",
    "        \n",
    "    elif choice == 10:\n",
    "        print(\"Thank you for using Calculator!!!\")\n",
    "        break; "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "434ebdda",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}